// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopMaster.Services.ProductAPI.Data;

#nullable disable

namespace ShopMaster.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241026123020_Update-image")]
    partial class Updateimage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopMaster.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Périphérique",
                            Description = "Clavier mécanique avec rétroéclairage RGB personnalisable, idéal pour le gaming et la bureautique. Conception robuste et touches programmables.",
                            ImageUrl = "https://borgiphones.com/wp-content/uploads/2024/05/clavier-mecanique-retroeclaire-rgb-spirit-of-gamer-xpert-k700-1.png",
                            Name = "Clavier Mécanique RGB",
                            Price = 89.989999999999995
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Périphérique",
                            Description = "Souris ergonomique avec 7 boutons programmables, capteur haute précision, idéale pour les joueurs professionnels.",
                            ImageUrl = "https://www.alarabia.com.tn/19082-large_default/souris-filaire-gamer-spirit-s-pm7-rgb-7-boutons.jpg",
                            Name = "Souris Gamer 7 Boutons",
                            Price = 49.990000000000002
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Affichage",
                            Description = "Écran LED de 24 pouces avec résolution Full HD, offrant des couleurs éclatantes et des angles de vision larges pour un usage polyvalent.",
                            ImageUrl = "https://mk-media.mytek.tn/media/catalog/product/cache/8be3f98b14227a82112b46963246dfe1/e/c/ecran-samsung-lf24t350fhmxzn-24-full-hd-75hz.jpg",
                            Name = "Écran LED Full HD 24\"",
                            Price = 159.99000000000001
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Ordinateur",
                            Description = "Ordinateur portable équipé d'un processeur Intel i5, 8 Go de RAM, et un SSD de 256 Go pour une performance optimale dans toutes les tâches.",
                            ImageUrl = "https://mtsplus.tn/2607-large_default/pc-portable-asus-i5-11e-gen-8go-512go-ssd-mx330-x515ep-br245t.jpg",
                            Name = "Ordinateur Portable i5",
                            Price = 699.99000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
