// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopMaster.Services.ProductAPI.Data;

#nullable disable

namespace ShopMaster.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241025214134_initial-migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopMaster.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Périphérique",
                            Description = "Clavier mécanique avec rétroéclairage RGB personnalisable, idéal pour le gaming et la bureautique. Conception robuste et touches programmables.",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Clavier Mécanique RGB",
                            Price = 89.989999999999995
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Périphérique",
                            Description = "Souris ergonomique avec 7 boutons programmables, capteur haute précision, idéale pour les joueurs professionnels.",
                            ImageUrl = "https://placehold.co/602x402",
                            Name = "Souris Gamer 7 Boutons",
                            Price = 49.990000000000002
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Affichage",
                            Description = "Écran LED de 24 pouces avec résolution Full HD, offrant des couleurs éclatantes et des angles de vision larges pour un usage polyvalent.",
                            ImageUrl = "https://placehold.co/601x401",
                            Name = "Écran LED Full HD 24\"",
                            Price = 159.99000000000001
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Ordinateur",
                            Description = "Ordinateur portable équipé d'un processeur Intel i5, 8 Go de RAM, et un SSD de 256 Go pour une performance optimale dans toutes les tâches.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Ordinateur Portable i5",
                            Price = 699.99000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
